language: haskell
ghc:
  # 7.4
  # 7.6
  - 7.8

before_install:
  # SDL2
  - (curl -O http://libsdl.org/release/SDL2-2.0.3.tar.gz && tar -xzf SDL2*)
  - (cd SDL2*/ && ./configure && make && sudo make install && cd ..)
  # rtld
  - git clone https://github.com/kkardzis/rtld.git && cabal install ./rtld
